apiVersion: v1
kind: Service
metadata:
  name: mcp-code-context
  namespace: sophia
spec:
  selector: { app: mcp-code-context }
  ports:
    - name: tcp
      port: 8081
      targetPort: 8081
  type: ClusterIP
