version: '3.8'
services:
  # Database Services
  postgres:
    image: postgres:15
    container_name: sophia-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sophia
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=sophia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sophia"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: sophia-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Vector Database for Embeddings
  qdrant:
    image: qdrant/qdrant:v1.6.0
    container_name: sophia-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Workflow Orchestration
  temporal:
    image: temporalio/auto-setup:1.21.0
    container_name: sophia-temporal
    ports:
      - "7233:7233" # gRPC
      - "8233:8233" # Web UI
    environment:
      - DB=sqlite3
    volumes:
      - temporal_data:/etc/temporal/sqlite

  # MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sophia-mcp-server
    depends_on:
      - postgres
      - redis
      - qdrant
      - temporal
    ports:
      - "8001:8001" # MCP Port
      - "8002:8002" # MCP Gateway Port
    environment:
      - ESC_ENV=sophia/dev
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MCP_PORT=8001
      - MCP_GATEWAY_PORT=8002
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - LOG_LEVEL=INFO
    command: python -m mcp_servers.unified_mcp_server
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  # Orchestrator Worker
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sophia-orchestrator
    depends_on:
      - temporal
      - mcp-server
    environment:
      - ESC_ENV=sophia/dev
      - TEMPORAL_HOST=temporal:7233
      - LOG_LEVEL=INFO
    command: python -m orchestrator.app
    volumes:
      - ./data:/app/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  temporal_data: