version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: sophia
      POSTGRES_USER: sophia
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  qdrant:
    image: qdrant/qdrant:v1.11.2
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  mcp_server:
    image: python:3.13
    command: uvicorn apps.sophia_api.mcp_server:app --host 0.0.0.0 --port 8000
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - SALESFORCE_ACCESS_TOKEN=${SALESFORCE_ACCESS_TOKEN}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  qdrant_data:
