app = "sophia-intel"
primary_region = "us-west-2"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/app/apps/frontend"
  url_prefix = "/"

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2

[env]
  PORT = "5000"

