app = "sophia-intel"
primary_region = "ord"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[env]
  GPU_TYPE = "none"
  LAMBDA_IPS = "192.222.51.223,192.222.50.242"
  auto_stop_machines = false
  min_machines_running = 1

[mounts]
  source = "sophia_data"
  destination = "/data"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[processes]
  app = "uvicorn main:app --host 0.0.0.0 --port 8000"

