# SOPHIA V4 Ultimate Autonomous Fly.io Configuration
# Clean, production-ready deployment with no tech debt

app = "sophia-intel"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "python:3.11-slim"

[env]
  PORT = "8080"
  PYTHONPATH = "/app"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/v1/health"

# Backend Processing Machines - Performance-8x
[[vm]]
  size = "performance-8x"  # 8 vCPUs, 16GB RAM
  regions = ["ord", "yyz"]
  processes = ["app"]

# AI Processing Machine - A100 GPU
[[vm]]
  size = "performance-4x"  # 4 vCPUs, 8GB RAM
  gpu_kind = "a100-40gb"   # A100-40GB GPU for AI processing
  regions = ["ord"]
  processes = ["app"]

# Persistent Storage
[[mounts]]
  source = "sophia_data"
  destination = "/data"
  processes = ["app"]

[deploy]
  release_command = "python -c 'print(\"SOPHIA V4 Ultimate Autonomous Ready! 🤠🔥\")'"

# No sandbox-specific configurations
# Production-ready autonomous AI deployment! 🚀

