app = "sophia-intel"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/v1/health"

[processes]
  app = "python3 sophia_v4_production.py"

[[vm]]
  size = "performance-8x"
  memory = "16gb"
  cpu_kind = "performance"
  processes = ["app"]

[deploy]
  strategy = "rolling"
  max_unavailable = 1

[restart]
  policy = "always"

[metrics]
  port = 9090
  path = "/metrics"

