app = "sophia-intel"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  QDRANT_URL = "https://a2a5dc3b-bf37-4907-9398-d49f5c6813ed.us-west-2-0.aws.cloud.qdrant.io"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["backend"]

[[services.concurrency]]
  type = "requests"
  soft_limit = 200
  hard_limit = 250

# Backend machines - Performance-8x (8 vCPUs, 16GB RAM)
[[vm]]
  cpu_kind = "performance"
  cpus = 8
  memory_mb = 16384
  processes = ["backend"]

# AI processing machine - Performance-4x with A100-40GB GPU
[[vm]]
  cpu_kind = "performance"
  cpus = 4
  memory_mb = 8192
  gpu_kind = "a100-pcie-40gb"
  gpus = 1
  processes = ["ai"]

# Frontend machines - Shared-2x (2 vCPUs, 4GB RAM)
[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096
  processes = ["frontend"]

# Persistent storage for Qdrant and logs
[[mounts]]
  source = "qdrant_data"
  destination = "/data"
  processes = ["backend", "ai"]

# Multi-region deployment
[deploy]
  strategy = "rolling"
  
[[deploy.regions]]
  name = "ord"
  
[[deploy.regions]]
  name = "yyz"

