[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmd = "uvicorn minimal_main:app --host 0.0.0.0 --port $PORT"

[build]
cacheKey = "build-minimal-$(date +%s)"

