[build]
builder = "DOCKERFILE"

[deploy]
replicas = 2
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 30
startCommand = "uvicorn ultimate_main:app --host 0.0.0.0 --port 8000"

[variables]
# Database connections (provided by Railway services)
QDRANT_URL = "${{Qdrant.QDRANT_URL}}"
REDIS_URL = "${{Redis.REDIS_URL}}"
NEON_DATABASE_URL = "${{NeonDB.DATABASE_URL}}"

# API Keys (from Railway environment variables)
OPENROUTER_API_KEY = "${{OPENROUTER_API_KEY}}"
GITHUB_PAT = "${{GITHUB_PAT}}"
DNSIMPLE_API_KEY = "${{DNSIMPLE_API_KEY}}"

# Application Configuration
NODE_ENV = "production"
PYTHON_ENV = "production"
LOG_LEVEL = "info"

# Security Configuration
CORS_ORIGINS = "https://www.sophia-intel.ai,https://api.sophia-intel.ai"
ALLOWED_HOSTS = "www.sophia-intel.ai,api.sophia-intel.ai"

# Health Check Configuration
HEALTH_CHECK_TIMEOUT = "30"
HEALTH_CHECK_INTERVAL = "60"

# Monitoring and Observability
PROMETHEUS_ENABLED = "true"
METRICS_PORT = "9090"

# Feature Flags
ENABLE_CHAT = "true"
ENABLE_RESEARCH = "true"
ENABLE_CODING = "true"
ENABLE_MCP_SERVICES = "true"

[environments.production]
variables = {}

[environments.staging]
variables = {
  LOG_LEVEL = "debug",
  CORS_ORIGINS = "https://staging.sophia-intel.ai"
}

