app = "sophia-memory"
primary_region = "iad"

[build]
  dockerfile = "../docker/production/Dockerfile.mcp"

[env]
  PORT = "8080"
  MCP_ROLE = "memory"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls","http"]

  [[services.http_checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout  = "2s"
    grace_period = "10s"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

