app = "sophia-research"
primary_region = "iad"

[build]
  dockerfile = "../mcp_servers/Dockerfile"

[env]
  PORT = "8080"
  SERVICE_TYPE = "research"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

