app = "sophia-code"
primary_region = "iad"

[build]
  dockerfile = "./fly/Dockerfile.code-standalone"

[env]
  PORT = "8080"
  PYTHONPATH = "/app"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "30s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"

