app = "sophia-research"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.research"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls","http"]
  
  [[services.http_checks]]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
