app = "sophia-context-v42"
primary_region = "iad"

[build]
  dockerfile = "fly/Dockerfile.context"

[env]
  PORT = "8080"
  MCP_ROLE = "context"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls","http"]

  [services.http_checks]
    method = "GET"
    path = "/healthz"
    interval = "10s"
    timeout  = "2s"
    grace_period = "10s"

[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

