apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-api
  namespace: sophia-intel
  labels:
    app: sophia-api
    component: backend
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sophia-api
  template:
    metadata:
      labels:
        app: sophia-api
        component: backend
    spec:
      containers:
      - name: sophia-api
        image: sophia-intel/api:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "5000"
        - name: HOST
          value: "0.0.0.0"
        - name: LAMBDA_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: lambda-api-key
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: openrouter-api-key
        - name: LAMBDA_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: lambda-cloud-api-key
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: github-pat
        - name: DNSIMPLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: dnsimple-api-key
        - name: QDRANT_URL
          valueFrom:
            configMapKeyRef:
              name: sophia-config
              key: qdrant-url
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: qdrant-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-api-service
  namespace: sophia-intel
  labels:
    app: sophia-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: sophia-api

