apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-mcp
  namespace: sophia-mvp
  labels:
    app: sophia-intel
    component: mcp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sophia-intel
      component: mcp
  template:
    metadata:
      labels:
        app: sophia-intel
        component: mcp
    spec:
      containers:
      - name: sophia-mcp
        image: sophia-intel/mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: github-pat
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: openrouter-api-key
        - name: MCP_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: sophia-config
              key: mcp-server-host
        - name: MCP_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: sophia-config
              key: mcp-server-port
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: mcp-logs
          mountPath: /app/logs
        - name: mcp-ssh
          mountPath: /app/.ssh
      volumes:
      - name: mcp-logs
        emptyDir: {}
      - name: mcp-ssh
        emptyDir: {}
      restartPolicy: Always

