name: sophia-mvp-production
runtime: python
description: SOPHIA MVP Production Infrastructure on Lambda Labs

config:
  lambda_api_key:
    type: string
    secret: true
    description: Lambda Labs API key
  github_pat:
    type: string
    secret: true
    description: GitHub Personal Access Token
  dnsimple_token:
    type: string
    secret: true
    description: DNSimple API token
  openrouter_api_key:
    type: string
    secret: true
    description: OpenRouter API key
