apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophia-mcp-servers
  namespace: sophia-intel
  labels:
    app: sophia-mcp-servers
    component: mcp
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: sophia-mcp-servers
  template:
    metadata:
      labels:
        app: sophia-mcp-servers
        component: mcp
    spec:
      containers:
      - name: mcp-unified-server
        image: sophia-intel/mcp-servers:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "8001"
        - name: HOST
          value: "0.0.0.0"
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: github-pat
        - name: QDRANT_URL
          valueFrom:
            configMapKeyRef:
              name: sophia-config
              key: qdrant-url
        - name: QDRANT_API_KEY
          valueFrom:
            secretKeyRef:
              name: sophia-secrets
              key: qdrant-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-mcp-service
  namespace: sophia-intel
  labels:
    app: sophia-mcp-servers
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: sophia-mcp-servers

