apiVersion: v1
kind: Service
metadata:
  name: sophia-api
  namespace: sophia-mvp
  labels:
    app: sophia-intel
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: sophia-intel
    component: api

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-dashboard
  namespace: sophia-mvp
  labels:
    app: sophia-intel
    component: dashboard
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: sophia-intel
    component: dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-mcp
  namespace: sophia-mvp
  labels:
    app: sophia-intel
    component: mcp
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: sophia-intel
    component: mcp

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-redis
  namespace: sophia-mvp
  labels:
    app: sophia-intel
    component: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: sophia-intel
    component: redis

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-postgres
  namespace: sophia-mvp
  labels:
    app: sophia-intel
    component: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: sophia-intel
    component: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: sophia-qdrant
  namespace: sophia-mvp
  labels:
    app: sophia-intel
    component: qdrant
spec:
  type: ClusterIP
  ports:
  - port: 6333
    targetPort: 6333
    protocol: TCP
    name: http
  - port: 6334
    targetPort: 6334
    protocol: TCP
    name: grpc
  selector:
    app: sophia-intel
    component: qdrant

