apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app: cert-manager
spec:
  acme:
    # Production Let's Encrypt server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@sophia-intel.ai
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: kong
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: cert-manager
spec:
  acme:
    # Staging Let's Encrypt server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@sophia-intel.ai
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: kong
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sophia-intel-cert
  namespace: sophia-intel
  labels:
    app: sophia-intel
spec:
  secretName: sophia-intel-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sophia-intel.ai
  - www.sophia-intel.ai
  - api.sophia-intel.ai
  - dashboard.sophia-intel.ai
  - "*.sophia-intel.ai"
  usages:
  - digital signature
  - key encipherment

