[build]
command = "pip install -r requirements.txt"

[start]
command = "python mcp_server.py"

[env]
PORT = "8001"
ENVIRONMENT = "production"

[healthcheck]
path = "/health"
timeout = 30
interval = 60
