# SOPHIA OpenRouter Model Allowlist
# Only these models are permitted for use in the system

allowed_models:
  # Primary models for production use
  - model_id: "openai/gpt-4o"
    name: "GPT-4o"
    provider: "openai"
    max_tokens: 128000
    cost_per_1k_input: 0.005
    cost_per_1k_output: 0.015
    use_cases: ["coding", "analysis", "planning", "general"]
    priority: 1
    
  - model_id: "openai/gpt-4o-mini"
    name: "GPT-4o Mini"
    provider: "openai"
    max_tokens: 128000
    cost_per_1k_input: 0.00015
    cost_per_1k_output: 0.0006
    use_cases: ["simple_tasks", "testing", "validation"]
    priority: 2

# Backup models (use only if primary unavailable)
backup_models:
  - model_id: "anthropic/claude-3.5-sonnet"
    name: "Claude 3.5 Sonnet"
    provider: "anthropic"
    max_tokens: 200000
    cost_per_1k_input: 0.003
    cost_per_1k_output: 0.015
    use_cases: ["coding", "analysis", "long_context"]
    priority: 3

# Blocked models (never use these)
blocked_models:
  - "meta-llama/*"  # Too expensive for production
  - "google/*"      # Inconsistent performance
  - "mistral/*"     # Not suitable for coding tasks
  - "*/gpt-3.5*"    # Deprecated

# Model routing rules
routing_rules:
  # Route by use case
  coding:
    primary: "openai/gpt-4o"
    fallback: "openai/gpt-4o-mini"
    
  analysis:
    primary: "openai/gpt-4o"
    fallback: "anthropic/claude-3.5-sonnet"
    
  simple_tasks:
    primary: "openai/gpt-4o-mini"
    fallback: "openai/gpt-4o"
    
  planning:
    primary: "openai/gpt-4o"
    fallback: "anthropic/claude-3.5-sonnet"

# Cost controls
cost_limits:
  daily_budget_usd: 50.0
  per_request_max_usd: 1.0
  warning_threshold_usd: 40.0
  
# Rate limiting
rate_limits:
  requests_per_minute: 60
  tokens_per_minute: 100000
  concurrent_requests: 10

# Monitoring
monitoring:
  log_all_requests: true
  track_costs: true
  alert_on_blocked_model: true
  alert_on_cost_threshold: true

