{{- range $serviceName, $config := .Values.mcpServices }}
{{- if $config.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $config.name }}
    component: mcp-service
    service: {{ $serviceName }}
  {{- with $.Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  - port: {{ $config.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ $config.name }}
{{- end }}
{{- end }}

