[build]
command = "pip install -r requirements.txt"

[start]
command = "python monitoring_server.py"

[env]
PORT = "8002"
ENVIRONMENT = "production"

[healthcheck]
path = "/health"
timeout = 30
interval = 60
