apiVersion: v1
kind: Service
metadata:
  name: sophia-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app: sophia-api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
  selector:
    app: sophia-api
---
apiVersion: v1
kind: Service
metadata:
  name: sophia-interface
  namespace: {{ .Values.global.namespace }}
  labels:
    app: sophia-interface
spec:
  type: {{ .Values.interface.service.type }}
  ports:
  - port: {{ .Values.interface.service.port }}
    targetPort: {{ .Values.interface.service.targetPort }}
    protocol: TCP
  selector:
    app: sophia-interface
