# SOPHIA Intel MCP Services Configuration

# Global configuration
global:
  namespace: sophia-intel
  imageRegistry: ghcr.io
  imagePullPolicy: IfNotPresent
  
# MCP Services configuration
mcpServices:
  telemetry:
    enabled: true
    name: telemetry-mcp
    image: sophia-intel/telemetry-mcp
    tag: latest
    port: 5001
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SOPHIA_MCP_HOST
        value: "0.0.0.0"
      - name: SOPHIA_TELEMETRY_PORT
        value: "5001"
        
  embedding:
    enabled: true
    name: embedding-mcp
    image: sophia-intel/embedding-mcp
    tag: latest
    port: 5002
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SOPHIA_MCP_HOST
        value: "0.0.0.0"
      - name: SOPHIA_EMBEDDING_PORT
        value: "5002"
        
  research:
    enabled: true
    name: brightdata-research-mcp
    image: sophia-intel/brightdata-research-mcp
    tag: latest
    port: 5003
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SOPHIA_MCP_HOST
        value: "0.0.0.0"
      - name: SOPHIA_RESEARCH_PORT
        value: "5003"
        
  notion:
    enabled: true
    name: notion-sync-mcp
    image: sophia-intel/notion-sync-mcp
    tag: latest
    port: 5004
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SOPHIA_MCP_HOST
        value: "0.0.0.0"
      - name: SOPHIA_NOTION_PORT
        value: "5004"

# Secrets configuration (references to external secrets)
secrets:
  name: sophia-secrets-enhanced
  keys:
    - openrouter-api-key
    - openai-api-key
    - elevenlabs-api-key
    - qdrant-api-key
    - qdrant-url
    - weaviate-admin-api-key
    - neon-api-key
    - github-pat
    - notion-api-key
    - brightdata-api-key
    - slack-webhook-url
    - dnsimple-api-key
    - lambda-cloud-api-key

# Service configuration
service:
  type: ClusterIP
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: kong
  annotations: {}
  hosts: []
  tls: []

# Monitoring and health checks
monitoring:
  enabled: true
  healthCheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    enabled: true
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

