FROM nginx:alpine
ARG VITE_BUILD_ID
ARG VITE_RESEARCH_URL
ENV BUILD_ID=$VITE_BUILD_ID \
    RESEARCH_URL=$VITE_RESEARCH_URL
COPY nginx-bulletproof.conf /etc/nginx/conf.d/default.conf
COPY dist/ /usr/share/nginx/html
EXPOSE 8080

