name: CI Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    
    env:
      ESC_ENV: ${{ secrets.ESC_ENV }}
      ESC_TOKEN: ${{ secrets.ESC_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Pulumi ESC CLI
        run: |
          curl -fsSL https://get.pulumi.com/esc/install.sh | sh
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - name: Verify secrets configuration
        run: |
          echo "=== Checking configuration sources ==="
          python tools/smoke_env_check.py
        continue-on-error: false

      - name: GitHub CLI auth smoke
        run: |
          gh auth status || (echo "::warning::gh not logged in in CI context (fine for PRs from forks)"; exit 0)

      - name: Run linters
        run: |
          ruff check . || true
          black --check . || true

      - name: Run tests
        run: pytest -q --maxfail=5 --disable-warnings