name: Deploy SOPHIA Intel to Northflank

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NORTHFLANK_API_TOKEN: ${{ secrets.NORTHFLANK_API_TOKEN }}
  PROJECT_ID: sophia-intel

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/dashboard/package.json'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Install frontend dependencies
        working-directory: apps/dashboard
        run: |
          npm ci

      - name: Build frontend
        working-directory: apps/dashboard
        run: |
          npm run build

      - name: Test backend
        run: |
          python -c "import backend.main; print('Backend imports successfully')"

      - name: Lint Python code
        run: |
          pip install flake8 black
          flake8 backend/ --max-line-length=120 --extend-ignore=E203,W503 || echo "Linting issues found"
          black --check backend/ --line-length=120 || echo "Formatting issues found"

  deploy-secrets:
    name: Setup Secrets
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Northflank CLI
        run: npm install -g @northflank/cli

      - name: Login to Northflank
        run: echo "${{ secrets.NORTHFLANK_API_TOKEN }}" | nf login --token

      - name: Create Secret Group
        run: |
          nf create secret-group \
            --project=$PROJECT_ID \
            --name=sophia-secrets-prod \
            --description="Production secrets for SOPHIA Intel" || echo "Secret group might already exist"

      - name: Update Secrets
        run: |
          nf create secret \
            --project=$PROJECT_ID \
            --secret-group=sophia-secrets-prod \
            --name=LAMBDA_API_KEY \
            --value="${{ secrets.LAMBDA_API_KEY }}" || echo "Secret already exists"
          
          nf create secret \
            --project=$PROJECT_ID \
            --secret-group=sophia-secrets-prod \
            --name=DNSIMPLE_API_KEY \
            --value="${{ secrets.DNSIMPLE_API_KEY }}" || echo "Secret already exists"

          nf create secret \
            --project=$PROJECT_ID \
            --secret-group=sophia-secrets-prod \
            --name=OPENROUTER_API_KEY \
            --value="${{ secrets.OPENROUTER_API_KEY }}" || echo "Secret already exists"

          nf create secret \
            --project=$PROJECT_ID \
            --secret-group=sophia-secrets-prod \
            --name=DASHBOARD_API_TOKEN \
            --value="${{ secrets.DASHBOARD_API_TOKEN }}" || echo "Secret already exists"

  deploy-api:
    name: Deploy SOPHIA API
    runs-on: ubuntu-latest
    needs: [build-and-test, deploy-secrets]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Northflank CLI
        run: npm install -g @northflank/nf

      - name: Deploy SOPHIA Intel to Northflank
        env:
          NF_API_TOKEN: ${{ secrets.NORTHFLANK_API_TOKEN }}
          LAMBDA_API_KEY: ${{ secrets.LAMBDA_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          DNSIMPLE_API_KEY: ${{ secrets.DNSIMPLE_API_KEY }}
          DASHBOARD_API_TOKEN: ${{ secrets.DASHBOARD_API_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
        run: |
          chmod +x scripts/deploy_northflank.sh
          ./scripts/deploy_northflank.sh

  deploy-dashboard:
    name: Deploy SOPHIA Dashboard
    runs-on: ubuntu-latest
    needs: [build-and-test, deploy-secrets, deploy-api]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Northflank CLI
        run: npm install -g @northflank/nf

      - name: Login to Northflank
        run: echo "${{ secrets.NORTHFLANK_API_TOKEN }}" | nf login --token

      - name: Update Dashboard Service
        run: |
          nf update service sophia-dashboard \
            --project=sophia3 \
            --env VITE_API_URL=https://api.sophia-intel.ai \
            --env NODE_ENV=production || echo "Dashboard service might not exist yet"

  health-check:
    name: Health Check Deployment
    runs-on: ubuntu-latest
    needs: [deploy-api, deploy-dashboard]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Wait for services to start
        run: sleep 90

      - name: Check API Health
        run: |
          echo "🔍 Checking API health..."
          curl -f https://api.sophia-intel.ai/health || echo "API not ready yet"

      - name: Check Dashboard Health
        run: |
          echo "🔍 Checking Dashboard health..."
          curl -f https://www.sophia-intel.ai/ || echo "Dashboard not ready yet"

      - name: Deployment Summary
        run: |
          echo "🎉 SOPHIA Intel Deployment Complete!"
          echo "📡 API: https://api.sophia-intel.ai"
          echo "🌐 Dashboard: https://www.sophia-intel.ai"
          echo "📊 Status: Services deployed and starting up"
          echo ""
          echo "🔍 To check status manually:"
          echo "nf get services --project sophia3"

