name: Deploy SOPHIA V4 to Fly.io
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly.io
        run: flyctl deploy --app sophia-intel --remote-only --verbose
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
      - name: Health check
        run: |
          sleep 30
          curl -f https://sophia-intel.fly.dev/ || exit 1
          curl -f https://sophia-intel.fly.dev/v4/ || echo "V4 endpoint not ready yet"
