name: Deploy SOPHIA Intel to Northflank

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test minimal workflow
        run: |
          echo "✅ Minimal workflow is working!"
          echo "Repository structure:"
          ls -la
          
      - name: Check if we can proceed to build
        run: |
          echo "🔍 Checking for frontend directories..."
          find . -name "package.json" -not -path "*/node_modules/*" | head -5
          echo "🔍 Checking for backend requirements..."
          find . -name "requirements.txt" | head -5
