name: Hygiene Bot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  hygiene:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Code formatting check
      run: |
        black --check --diff .
        isort --check-only --diff .
    
    - name: Linting
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Environment sync check
      run: |
        python -c "
import pathlib
import re
import os

keys = set()
for p in pathlib.Path('.').rglob('*.py'):
    try:
        txt = p.read_text(encoding='utf-8', errors='ignore')
        keys.update(re.findall(r'os\.getenv\([\"\'']([A-Z0-9_]+)[\"\''], txt))
    except:
        continue

env_file = pathlib.Path('.env.example')
if env_file.exists():
    env_content = env_file.read_text()
    for key in sorted(keys):
        if key not in env_content:
            print(f'Missing environment variable: {key}')
"
