name: Infra Preview (Pulumi)

on:
  pull_request:
    paths:
      - "infra/**"
      - "scripts/**"
      - "k8s/**"
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: infra-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Skip on forks (no secrets)
        if: ${{ github.event.pull_request.head.repo.fork }}
        run: |
          echo "Skipping preview for forked PR (secrets unavailable)."
          exit 0

      - name: Preflight env checks
        shell: bash
        run: |
          set -euo pipefail
          if [[ -z "${{ secrets.LAMBDA_CLOUD_API_KEY }}" ]]; then
            echo "::error::Missing secret: LAMBDA_CLOUD_API_KEY"
            exit 1
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Pulumi
        uses: pulumi/actions@v5
        with:
          pulumi-version: 3.x

      - name: Pulumi login (local backend when no Pulumi Cloud token)
        shell: bash
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          set -euo pipefail
          if [[ -z "${PULUMI_ACCESS_TOKEN:-}" ]]; then
            pulumi login --cloud-url file://$HOME/.pulumi-local
          fi

      - name: Install infra deps
        working-directory: infra
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Select/init stack
        working-directory: infra
        run: |
          pulumi stack select dev || pulumi stack init dev

      - name: Pulumi preview (diff)
        id: prev
        working-directory: infra
        env:
          LAMBDA_CLOUD_API_KEY: ${{ secrets.LAMBDA_CLOUD_API_KEY }}
        run: |
          set -euo pipefail
          pulumi preview --non-interactive --diff | tee ../preview.txt
          echo "out=$GITHUB_WORKSPACE/preview.txt" >> $GITHUB_OUTPUT

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: pulumi-preview
          path: preview.txt

      - name: Comment preview summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('${{ steps.prev.outputs.out }}','utf8');
            const short = body.length > 60000 ? body.slice(0,60000) + "\n\n[truncated]" : body;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "### Pulumi Preview (dev)\n````txt\n" + short + "\n````"
            });
