name: Deploy SOPHIA Intel to Railway

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/railway-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
        
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      run: |
        cd backend
        railway login --token $RAILWAY_TOKEN
        railway project create sophia-intel-backend || true
        railway up --detach
        railway domain generate
        echo "✅ SOPHIA Intel backend deployed to Railway!"
        
    - name: Get deployment URL
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        cd backend
        railway status
        railway domain

