name: Roo Modes Validation

on:
  push:
    paths:
      - '.roomodes'
      - 'scripts/validate_roomodes.py'
  pull_request:
    paths:
      - '.roomodes'
      - 'scripts/validate_roomodes.py'

jobs:
  validate-roomodes:
    runs-on: ubuntu-latest
    name: Validate .roomodes Configuration
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install PyYAML
          
      - name: Validate .roomodes file
        run: |
          python scripts/validate_roomodes.py --json
          
      - name: Check file encoding
        run: |
          file .roomodes
          python -c "
          with open('.roomodes', 'r', encoding='utf-8') as f:
              content = f.read()
              if not content.isascii():
                  print('⚠️ Warning: Non-ASCII characters detected')
                  exit(1)
              print('✅ File is clean ASCII')
          "
          
      - name: Verify expected modes exist
        run: |
          python -c "
          import yaml
          with open('.roomodes') as f:
              data = yaml.safe_load(f)
          
          expected_modes = ['architect', 'builder', 'tester', 'operator', 'debugger']
          actual_modes = [m['slug'] for m in data['customModes']]
          
          missing = set(expected_modes) - set(actual_modes)
          if missing:
              print(f'❌ Missing expected modes: {missing}')
              exit(1)
          
          print('✅ All expected modes present')
          print(f'Modes found: {actual_modes}')
          "
          
      - name: Generate reload scripts
        run: |
          python scripts/validate_roomodes.py --auto-reload
          
      - name: Archive reload scripts (if generated)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: roo-reload-scripts
          path: |
            scripts/roo_force_reload.sh
            .roo_reload_log
            .roomodes.checksum
          retention-days: 7