apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: sophia
spec:
  replicas: 2
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: ${IMAGE_API}
          imagePullPolicy: Always
          ports: [ { containerPort: 8080 } ]
          env:
            - name: LOG_LEVEL
              value: info
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
